# Generated by Django 5.1.2 on 2024-10-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_delete_authentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
